version: '3'

services:

  dispatch_console:
    build: ./
    image: dannychen98/tfs_dispatch_console:v1.0.0
    environment:
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"

  abp_host:
    build: ./
    image: dannychen98/tfs_api:v1.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"
      App__ServerRootAddress: "https://tfsexp.com:44311/"
      App__ClientRootAddress: "https://tfsexp.com:4200/"
      App__CorsOrigins: "https://tfsexp.com:4200"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always

  abp_ng:
    build: ./
    image: dannychen98/tfs_ms:v1.0.0
    ports:
      - "4200:80"
