version: '3'

services:

  dispatch_importer:
    build: ./
    image: dannychen98/tfs_dispatch_importer:v1.0.3
    environment:
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"

  dispatch_validator:
    build: ./
    image: dannychen98/tfs_dispatch_validator:v1.0.3
    environment:
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"

  item_tracking_generator:
    build: ./
    image: dannychen98/tfs_item_tracking_generator:v1.0.2
    environment:
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"

  item_tracking_updater:
    build: ./
    image: dannychen98/tfs_item_tracking_updater:v1.0.1
    environment:
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"

  abp_host:
    build: ./
    image: dannychen98/tfs_api:v1.1.23
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/etc/ssl/certs/fullchain.pem"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/etc/ssl/private/privkey.pem"
      ConnectionStrings__Default: "server=rm-3ns047wo8pox13094go.mysql.rds.aliyuncs.com;port=3306;database=tfsdb;uid=tfs_admin;pwd=tfs@1234"
      App__ServerRootAddress: "https://app.tfsexp.com:44311/"
      App__ClientRootAddress: "https://app.tfsexp.com:8443/"
      App__CorsOrigins: "https://app.tfsexp.com:8443"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "https://+:443"
    ports:
      - "44311:443"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: always

  abp_ng:
    build: ./
    image: dannychen98/tfs_ms:v1.1.18
    ports:
      - "8443:443"
