version: '3'

services:

  dispatch_console:
    build: ./
    image: dannychen98/dispatch_console:v1.2.15
    environment:
      ConnectionStrings__Default: "server=65.21.224.66;port=3306;database=SMPDb;uid=droot;pwd=snd@1234"

  abp_host:
    build: ./
    image: dannychen98/smp_api:v1.2.10
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "server=65.21.224.66;port=3306;database=SMPDb;uid=droot;pwd=snd@1234"
      App__ServerRootAddress: "http://65.21.224.66:44311/"
      App__ClientRootAddress: "http://65.21.224.66:4200/"
      App__CorsOrigins: "http://65.21.224.66:4200"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always

  abp_ng:
    build: ./
    image: dannychen98/smp_ms:v1.2.11
    ports:
      - "4200:80"
